version: 2

sources:
   - name: raw #Renaming as an alias
     schema: gz_raw_data #Path of the table in BQ
     description: greenweez raw data source #optionnal 
     tables:

         - name: sales #Renaming as an alias
           identifier: raw_gz_sales #What is the exact name of the table in  BQ
           description: sales of greewneez / we have one row per product_id found in each order_id
           #freshness testing
           loaded_at_field: "CAST(... AS TIMESTAMP)"
           freshness:
            warn_after: {count: 90, period: day}
           columns:
             - name: "(orders_id || '-' || pdt_id)"
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: date_date
               description: date of purchase
             - name: orders_id
               description: indvidual order identifier
             - name: pdt_id
               description: individual product identifier
             - name: revenue
               description: revenue generated by each order
             - name: quantity
               description: quantity of each product sold


         - name: product
           identifier: raw_gz_product
           description: purchase_price by products_id
           columns:
             - name: products_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null
                 
         - name: ship
           identifier: raw_gz_ship
           description: ship_cost by orders_id
           columns:
             - name: orders_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null